language: go
go:
- 1.13.x
before_install:
- go get -u github.com/mattn/goveralls
script:
- export GO111MODULE=on
- make
- make cover
- goveralls -coverprofile=.cover/all.merged -service=travis-ci
env:
  global:
  - secure: cc1Lquck6/m3CVkHkDoKXaSlG7aajWFv/U55b+6qOlTpaXj2Ux9moQr+49SYgjXBY6gQjGN3ZBOEFsoJYtnAe3VlpBTyxu+MXsocWdPZBDkU5U7hgcS1PXA0jwksFJ8LTFau/LeseizYPubeYRwKauVDvjQ45CjegbC/A6+Pty8Ecsdr2kK5qXg99l9u47nbluhGfH7skYSUdMO2RHsr2Cc1KwpGbx9HICDwyZi2Otg0dbH3jwaUPYNuebiNOBSsHFRSGIGPtsXu4KAWW8l0L6nnTB+R2V7Z9NSOY/0hQS+ISEvp48EHQ66qEa0Fb15pJnyx6ARJtFMKdxkelDUncbCDHSX6FJoOucmeggWdS+I7S/QimYes61hh5cO4iV4/XsnUqci9iVsbV4PwlJhJAFaBd3Jv/1D9ri/ljKHUePDCG9RVLZcnKJxEPUdht4VJ8CmWT8NxuVDZ/HJf3krWq90MJRYB8F4TT1bQpubWf7XGRG829PDkOL07iNhRTvBToLL7T+LEnUfHDZbl71TsnrxboqIzmZxDN+gX82WY8gmasrronZ/nYcGDFTYpFB6PooCmsmlc3hGNljQl0ADIecwbuTcxPJmVpB2II8RwStPtAMufFPfKUvXfS7xjuMINMMpPcSYLiH6sVXHh6G9E+8/hDmPXDNjyeXEMWc/uvSE=
